### ISSUE TITLE
Capital P Dangit!

### ISSUE THREAD

**Issue by BFTrick** [tomvdv/atom-wordpress#2]
It looks like the package isn't named correctly. I see `Wordpress` instead of `WordPress`. I tried seeing what setting controls it and I can't find it. Is this something Atom capitalized automatically?

![settings_-__users_patrick_documents_woothemes_test-site_wp-content_plugins_woocommerce-branding](https://f.cloud.github.com/assets/1065372/2431945/3127d184-ad4b-11e3-8186-257ca3cdaeeb.png)

**Comment by tomvdv** [comment]
> Is this something Atom capitalized automatically?

Looks like it, in the in-app package browser anyway. Package names (defined in `package.json`) seem to be transformed into title-case, and dashes are also removed, e.g. "language-sql" is displayed as "Language Sql".
It's spelled correctly on the package's page at https://atom.io/packages/wordpress.
